---
# yaml-language-server: $schema=https://crd.movishell.pl/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-stack
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: media-stack
  interval: 30m
  path: ./kubernetes/media-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: storage
    - name: network
  postBuild:
    substitute:
      NAMESPACE: media-stack
      DOMAIN: ${DOMAIN}
      TIMEZONE: ${TIMEZONE}
      LONGHORN: ${LONGHORN}
      LONGHORN_DUAL: ${LONGHORN_DUAL}
      LONGHORN_SINGLE: ${LONGHORN_SINGLE}
