apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-secrets
resources:
  - authelia.enc.yaml
  - cloudflare.enc.yaml
  - grafana.enc.yaml
  - immich.enc.yaml
  - lidify-secrets.enc.yaml
  - longhorn-backup.enc.yaml
  - longhorn-crypto.enc.yaml
  - minecraft-rcon.enc.yaml
  - navidrome-lastfm.enc.yaml
  - nextcloud.enc.yaml
  - slskd-creds.enc.yaml
  - slskd-wireguard.enc.yaml
  - sonobarr.enc.yaml
  - tailscale.enc.yaml
  - tandoor.enc.yaml
