apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-secret
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cOZC3VhM+HJE4qFzcKOp2jvNzE9SYIJ2kw==,iv:6xfQc51aU831wA9alm5lofqF8/oZ1i2fgOhKgWUSc2c=,tag:WsnCiF6nt9+D4rNqkzMYEA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:s4y7IlZ1yLtui/M2diHTY0zZEBlS+7edXD6UjwN+0Q==,iv:ZbY9IYe/9xQo6ALsD+yG6cJxNsBiKcxl+WJULpeh6o0=,tag:MJDTSVYyRQUynoFI22d+QQ==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:DTYq5DIaIxDoX3716dBTY2+wbeRHDVRgeqZqix3B+FDKMhS0xeM1yug=,iv:bUxEo0Q2sGqvpFtQnCNOK2H64Z8Guoe0aVjlevead/k=,tag:mfS1mlxCvD3DZ2Msz4y0fA==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbnNzdmNtTHhLUjJxRGp1
            VGpCbHF5QmJpdVMzN1BYQUV3K2U0QlpHdkVVCi94MGdxWnl1T0xiQkM3YXVtMkFH
            U3BLbUlVeFY2WXErRnUvMFZnKzBnb2MKLS0tIGdjdGJNV2paY0ZRQW1pUEFCb0hF
            Q2QzdFF5T0pTbDJHMFg1ZUwvUVBCNTgKlTBLaYBZFWUUKP8uqnAiLRFXfeRuUtR0
            8fOy5Var+oL8UJ+m2GhakWq9S9LdvSWOqIdoVwwZTqvpuZsh3Yk/hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-28T23:56:24Z"
    mac: ENC[AES256_GCM,data:zzkdEGJU1rp9p31ChvAgCtxbUromdYkI811WYQEWvEcN1OTris6jAnfPQ3AYpYyRQ3lzijiI0f5q8zw5SaClB4wIhQSEtmfXi6KwADGQ1UVI4VEH2WxTJzwAhI1EvGPJmEb0/zFWrg3J2vI0Z+uBgFvo8qKGPirKaC4xOl1Go4M=,iv:5woTXNA+aBl08XheXYrv6E1QPpLWpMU9yoK+1J9c/qw=,tag:HFCyVtza0yZAWRKGGIVBDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
