apiVersion: v1
kind: Secret
metadata:
    name: longhorn-crypto
    namespace: longhorn-system
stringData:
    CRYPTO_KEY_VALUE: ENC[AES256_GCM,data:2C8Ibtjw8LwiQailhUgo/xMfBmoGMdRZWZtnm2B/A36heRr2sBB39+UDC6U=,iv:0dWIZ6cTrPBoStk8DDOTyKCmE/3SKPvX0WPzFBuCF3Y=,tag:o2Dc+fMFWYWPVIUcqUwi6A==,type:str]
    CRYPTO_KEY_PROVIDER: ENC[AES256_GCM,data:MNJ86ihB,iv:qAGcIqpIK6QkfCuc0QYbdWROzmWzU5XPv84LORbcOlU=,tag:yllUvlnK/ywnLPZzQ+cdvg==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNkFHK05jVHhLV0ZEeElv
            azh0dTlNSEFHNkhKdkQ1Qm4wWnJhUmFzR0NJClRHOE53Z3M0c3FWMmN3c1IxZlZK
            RHZkL2ZzNUFRNlpNdzcrWWUyWDhpczQKLS0tIEh5dDZpK21Dc2JWTVRFdVRDa1dp
            cUVQZ1NDZnQrMXFpWlhwQyt6SzAwYkUKFhe76/w+HkydpwV0wOJeEMt2/BN+QCf7
            osUClelnlHn4OFprZ0quKn/OJoGWPSwZy8l56yFT5rnOomamIV/pgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-07T17:27:25Z"
    mac: ENC[AES256_GCM,data:N6idMURvEORzBjaue/ala480GEgVytPsRDTnAgVbUK0ragCuJ8r9nf8pMOGzFSShaqI1WjCpgPBFZpvmZqpaWK+2e4lpFEPHv8DU5+/9XCe17Aemge4ddNKNPc7JKxWTZRpdXCeI2+IXHbHW0hXl3m4FFLex7EJekSx3J/U3W5A=,iv:0r1QtUroaw2r6pWi55U6tJ5VKge+HeCTzZSfEgt7anA=,tag:QTO/iBTaFb9fwYpTdmSGIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
