apiVersion: v1
kind: Secret
metadata:
    name: slskd-soulseek-creds
    namespace: media-stack
type: Opaque
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:Roz++gIg97NJST3piw==,iv:puqlqTvQU6FiNn0oxoH4paQ3rahcAVUISuuEbb/uqyE=,tag:v9JNoN4NzHZr17HVf2nawg==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:1O8BLvR+Jn4ECpDaCDPCSsav+QY=,iv:oaUYmgf9Xhgi1YBLLh7PngXrF7pQd2FF1oe2x3EeEH0=,tag:5PLlaYiTmgm63Y+f+or/uA==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TVY5aEVqRklJTzhqNkJX
            YUdIdHYxOHVXUGRZK0pZc2hUVnZ2Zk5VTjI4ClhrdjhyY1AyVGJPaEthRDJDSWJM
            N3hDelk1Yjd5TlZ3bGJvY1ErdWgzR00KLS0tIGdERlNHQ2hZQmpOQWxhT1l0NEl3
            L0VPdmtCVytYclBzWWQvQXlhSzcxcjQKpERybPgilb5IIkjWGtKSL+Mj8jtAyVfX
            DGYS04x73PM+UxOm+ONl6O5xl9kdlz+ZXkL3shzi9BwQlqCbepddnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T13:12:49Z"
    mac: ENC[AES256_GCM,data:z3p+xIsjiKDRPz+A0TNXW0B0+BOExdtVP0oueHJUABmCOBrIEYorYOrcmeDBsrecP96W61Svw2SKZKNnx1bfwKx5FI+RJLex70xMI0YoEgpcQSq6sxjrdlw6qzLc5Cb8+lYIbx0kP9qquglz+A8f1NCpvEFWuH3pw0IcAe+pf+M=,iv:qKezqj03JNkZGWQZBPfTufrtRLICNV8v0ZN+rLKX1jQ=,tag:9Ps+ykdETeT3aSZwuINUkQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
