apiVersion: v1
kind: Secret
metadata:
    name: sonobarr-secrets
    namespace: media-stack
type: Opaque
stringData:
    secret_key: ENC[AES256_GCM,data:dPiGIN5oEMKBD6xKnGaVmM72iY/RA4EOZmimMLd9sCpqTRP45J0eFag7A+Q=,iv:/ugsfz0Nskyq+b5SurGD4e09L7aYpslnEfpzBg2Khu4=,tag:+3MI7uiA1BWxZ+vATZRmhw==,type:str]
    last_fm_api_key: ENC[AES256_GCM,data:/CJsGr1KxdPGhcyhLAUTesoiDPxdaMoMFFs8CqOGNgc=,iv:C+TdJW3lDX1o42AAIc7k/dCKeVEk+ySKRIpjufDJ+is=,tag:+qX0YIWdZ7Osnc0ettNbBw==,type:str]
    last_fm_api_secret: ENC[AES256_GCM,data:XUTLQtclIWwONrUQwd7mZTRbZ25Wl3qAVzgf9MgICF8=,iv:BUzUi0SEtPTurEYf4cWJXPe4gm+Vkvvq861OazVPjUk=,tag:XjdnTpDSEM2oJEkOZ1ngRg==,type:str]
    lidarr_api_key: ENC[AES256_GCM,data:GvmzC4BfMzmLF6KKT0jaCBAapmzB++z60GuXLusjNMo=,iv:RthiZOQ7Y2tUeae+80weTMHV1S4IOUDY8C0s4S9v1m4=,tag:i7b3MR0jKDfvZB1CHvJsag==,type:str]
    sonobarr_superadmin_password: ENC[AES256_GCM,data:IoTiSdx3A6M2ichCze8STG9NE0NNUiBQaVt+ZsHlbd8myd+h4pyzlSRxGw==,iv:L8DuHJ9VMI+XSYRNh6mDrDGKCc6q2pdXpQ1GDwbADA8=,tag:GRZjS61ckFUaAOWm+qlezQ==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU21VTk5VSzZ5d2J1TERq
            VHJvS3hVRXVndTlVdlE0M3lIbkVudTdiMDJJCmI3aFNXY0VENnF6eUdkU1c5VlBr
            TVRlSW5SWm9UbGkvYlFRNUh1WDR6bHcKLS0tIFlWWUpHUEVkdGZhQ3djbE11TERP
            dTZldzJsYXdDUURiY09UWEVoL2JSTlkKIR7lNZuz8Rhbdiol3FXx/95BDvXcJ/fu
            1MmjXjyrwUsQ8mGMFzOZUK+iHk+30CKTONm6UaYBpN0Y7MR+eM8A4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T22:47:47Z"
    mac: ENC[AES256_GCM,data:cwUvsGmj9pgyzE3espaTkLUl/NgGRoSJLnBqwn/sffN4dtgXzCO/iU0aVVpKGVHwGMqM3AgpcyBm1j62lqSPT1csNQL7U5zD3FzM+TsaL3ITMgaXblzRkedpC9k8vSCUlpBDMjxroCzj2iHeikwusCK+7m7Xql0H6vx6eTyN6go=,iv:p4V8xnz1yPnekmUk3ybHjGTNGfDW1YNYQ+QTRgFVE/Q=,tag:ETiulxcyCWhIldSeEraihA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
