apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespaces
  - ./immich
  - ./media-stack
  - ./pihole
  - ./tandoor
  - ./nextcloud
  - ./monitoring
  - ./home-assistant
  - ./media/books
  - ./media/music
  - ./dashboard