apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:g1KIw5BsrDa+0jweJ7HmetaT/tTM9xEgYfHwVkakeoi7P3V4+D9lNohpVsv4cM9m8DPJxu/owy2U+GHLnzsT6w==,iv:Lp51ANYcZzYZl7AKU71LBOhpZnpnaDGkWiLdX7mmGcU=,tag:vQAAl77uGtSkcDkLncjJsw==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UEFSNVNGUXpLaDV6dFhX
            OG0rcjg0Rzdsb3ZTSnJhN2J4OXlDUkJkU0NnCjByZDh2bExpYzBpR1pwOGhqUzM5
            cFJxUFkzU3dSRk5jUk1PN0FWUzZZQXMKLS0tIHQ3RXBZT3JhRVpvaUZFUVJqZ2ZQ
            ZS8xS25ZZ2hMbXBHREx3d1drSDVxbEEKurSICzs8bp80VfZGjdtsvEgUhs12eBlD
            1/CrXyQgary5P5KaNXNwtAsvpUYaa3gxS0/bqy4Ni2OofcWQMGHOCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T22:07:14Z"
    mac: ENC[AES256_GCM,data:fN4XSbyodM9PMeCeYCvpWMgkvdJXYL9h4eARCtpH9uwX/d90BYHvNs1D4P+uBB3lndVecP/pNPJ5cc2nFs4jNkgw5JFjNaoVRC9tkW0cR9fChx90yg8QYcqkhOmjW1SslL9fAlYLgENjrOgA4zEdEkTDHkuCDOJ0joomGqoS044=,iv:fQ9/5f6f77xodgEdiHfQcEPPg57tNpLhnWn+vIv+cgc=,tag:dKOqEjMsFDsLXotDGVCfaw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
