apiVersion: v1
kind: Secret
metadata:
    name: obsidian-sync-secret
    namespace: obsidian-sync
type: Opaque
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:cXenvMg=,iv:2cREP19d2WA9C8k9FtCwWh5kjfyBKwF2M5ZC7JLrEDY=,tag:JIBrWyGvl6K/Kgz88V12sQ==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:QFJ+9qQR4+s5oaX80WK+1asVGhAcxhLPYTs3xew=,iv:t75jb7Hxw0JkojZnySNAi49c4TAaZDgOyjQlaNzcmgE=,tag:OdQ9JUQbZQfw6lBS9Fa5Qw==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSFZKVlFDbHpYeitVd1lK
            dnBFVTlxRFNkdThFOEg1Q3R3ZWpJdTk5QTFNCkxndEFaRXZoWW92TzlpY0Y3TFds
            bzlsRTlzdEgxazlqVTRLd3Zzb2I3YVEKLS0tIER1ajduTHZQcThUWnk0ekVjcENL
            TWZ0YzVTa3VCS09KdjdTRlVCNEZ0QjgKS7YXtg7bfh/QPDERAfN/mGd7VATBzTQm
            Yk9ckhGRIMDlbKM0Dl8mgkWlKRNRTCtr4dQqLs7PedaeaqKCXY8tJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T12:37:10Z"
    mac: ENC[AES256_GCM,data:jEQkDk7u/CR6wa4Wrr0/Ud74uudXgRJSvv5mlFCc8UafBTXohkmjVizbzBn3DmErPkW5qziJsiVfZWAPCsgdTvUmNrBP7l8WwbeMTdC5RLygLcWeWAv/6HzmXAymP9WEbdYL8LL11I4mMRo1U48NbCwvuAe/eOYdHRdyoF+TAU0=,iv:FIb+Ge4qjN47kggBDl9ZA/o2m6kDnC35NA8a4+2J3W8=,tag:fYhJN9kxK3Bpo9QeIEn3yA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
