---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLSYNC_CLAIM}
  annotations:
    volsync.backube/privileged-movers: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY}
  storageClassName: ${VOLSYNC_STORAGECLASS}
