apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freshrss
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - api-service.yaml
  - deployment-api.yaml
  - glance-proxy-script.yaml