apiVersion: v1
kind: ConfigMap
metadata:
  name: booklore-config
  namespace: books
data:
  TZ: "Europe/Berlin"
  BOOKLORE_PORT: "6060"
  DATABASE_URL: "jdbc:mariadb://mariadb:3306/booklore"
  DB_USER: "booklore"
  MYSQL_DATABASE: "booklore"
  MYSQL_USER: "booklore"