apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore
  namespace: books
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
  ingressClassName: traefik
  rules:
  - host: books.pxldi.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booklore
            port:
              number: 6060
  tls:
  - hosts:
    - books.pxldi.de