---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tandoor
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: tandoor
  interval: 30m
  path: ./kubernetes/selfhosted/tandoor/tandoor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: tandoor
  wait: true
  dependsOn:
    - name: tandoor-postgresql
  postBuild:
    substitute:
      APP: tandoor
      HOSTNAME: recipes.${DOMAIN}
      TIMEZONE: ${TIMEZONE}
      LONGHORN: ${LONGHORN}
      LONGHORN_DUAL: ${LONGHORN_DUAL}
