apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - namespace.yaml
  - storageclass-dual-disk.yaml
  - storageclass-encrypted-dual-disk.yaml
  - storageclass-single-replica.yaml
  - storageclass-ssd.yaml
  - recurring-snapshots.yaml