apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.enc.yaml
  - tailscale.enc.yaml
  - homepage.enc.yaml
  - tandoor.enc.yaml
  - authelia.enc.yaml
  - cloudflare.enc.yaml
  - nextcloud.enc.yaml
  - grafana.enc.yaml
  - minecraft-rcon.enc.yaml
  - longhorn-backup.enc.yaml
  - longhorn-crypto.enc.yaml
  - navidrome-lastfm.enc.yaml
  - slskd-creds.enc.yaml
  - slskd-wireguard.enc.yaml
  - lidify-secrets.enc.yaml
  - hardcover.enc.yaml