apiVersion: v1
kind: Secret
metadata:
    name: slskd-vpn-config
    namespace: media-stack
type: Opaque
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:D9C98CZyIOVd,iv:VIu9JFZvKLhFACoXp+FDQSflPzbI3IZf4BtH+ak60oY=,tag:UBK3913BVhFeRJRjmlkLdQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:1xVKpr9Sn2No,iv:kasfCSUT2HB9Xn8XCZJV7zcZxZ0I4X5/cE0SSS8T6GE=,tag:h+NDGzRcsAnIaq5K/wASpw==,type:str]
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:NF8kBNKYrkfTunMogH61a7iKkzh7H5iRc5U4lgnFyVW9LdBkXNYRg6x6gus=,iv:1YNx4g+Lp6bFXNF1Ydrvqr+8zpeM/Ces6tlfbwEpxZE=,tag:O7+VTdQG7BoqKadQV7Z6OA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:T2N3SRoUH16y+FDV1RBbAHEVUQI3ZoNJ7vp1fj1GvZaZv/8YNL3FYgX+IMc=,iv:mHVZz6wW7/TklGNw+oDuRRkst1d5mYIyYmIDCzZ1AvE=,tag:YUV2ZC8RD0lh/qlsP+3khw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:OJDNoxKGNOwsYPo=,iv:HxjilFmCgRqVTVFtppTfcdzgRP2B9PrF1u07HInU6A8=,tag:xPBNMKZFprbaZikK8S9s3Q==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:HAq9mHWZSoNi/sw=,iv:JksUKP6bs48RY0lu+Dgat8cMCCwjVVpecjWFdCPYbDE=,tag:+KcdoqvrAS8edqltaau1nw==,type:str]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:sLnywm+WWmErlIEm4g==,iv:ykKWL84XI5PM6ex6oaImoUi5Pys/cbiKezMcdpdcDBo=,tag:QdcO3Cz8rB9pYsyg461sEQ==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:qnbqFUsdkbfpMIW4krH2YetO49s=,iv:dbWKjb2OgwhE7X1DM2fjLZiAPmlQSU4mPPRB301YKsg=,tag:mbyc+RYdgKENqW3YTLGnQQ==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVkZ1WkQvU0pNRXJ2Wlp2
            bXhnNWZNMGY2N0ZOckU4OUhuN3VLdnZHUmpRCkVoV244bDdKR1YvZ2NobjhjblF1
            aG5paUkyQTRwcnFHc2RYa0MxK1M5R2cKLS0tIC9KRVVPblU5YTZncWpFcnNTTWNt
            MXdlOTRyMVRUWVc3VXFmbUg2UXhZVm8K2JSUXugmH+gxVyT89bBGwa8pjQgLTqS+
            FsXW+4bEuCt/M+Gu+1JJgabnRPHrTh2N3eL4kc08HOqOQBYB3AeRCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-11T12:33:40Z"
    mac: ENC[AES256_GCM,data:8Et25urG4+LOzp9JoAWriR22bRZDArLPnscAU4H6J8YRsKWazohVj6M72JVk/aS1GIWlw92hbXoGqeDAR8ipxw+pgOe8tpevEJVmzsXeSUiG3L7Uca7JVO0o6Wf5f5CODo390Ct5Fj3lDqTq7tsTu4ZLWOyiGb1d3YVDvjGCs1E=,iv:lKI8gF5uBx2jiCx7JgX5UAOTvmlEvnaGsAtvD3a5N8o=,tag:eSendGQRXgMYqIVnfFUtOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
