apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-vanilla-server
  namespace: minecraft
spec:
  suspend: true
  interval: 30m
  chart:
    spec:
      chart: minecraft
      version: '5.0.0'
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: minecraft-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3