apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - immich.yaml
  - media-stack.yaml
  - pihole.yaml
  - tandoor.yaml
  - nextcloud.yaml
  - monitoring.yaml
  - home-assistant.yaml
  - glances.yaml
  - obsidian-sync.yaml