apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: music
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - navidrome.yaml
  - slskd.yaml
  - soulsync.yaml
  - lidarr.yaml
  - service.yaml
  - ingress.yaml
