apiVersion: v1
kind: Secret
metadata:
    name: music-config
    namespace: music
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:n8XDQ2eb4Ausl2drdS/IAwRAjpf+gKgeAYtZVp/HM+dPWP5+3Ivxo+3KM3DAX9mPKwW61BBlywOymYryHPtWZX1NC5v5eAFfBLdpz6ZlT7P+tqvm/4TCqlM9b/FAEU4+QwuXGom92323mP6yAbmUGQoLhVwH6iV2Evqh2wAa4SFqYCBsguKnhcE9Csh4KF6qp833OdANgxTKwJwZmHDh4H73yetTz6xn8CFasD4I7WqRrzpNevDJP1k2GrNAYMWyYKdwv54aTzGFscAPGHHkiOVRGUnBJWjXFGIUZY6GeOEywEiW04kubJlXbO2Oyddpuc4V824ioHu4TP9x3r8Fw+lTgHgKD/SX6wtUGEYX5oNf7q2LKuuZLF6xxlBWB4LwAeVV4l5IDu6p2n2ay71q8Ib8zqtWdxhXedBoHCb5jGOjW0/mgDG6/rJ5ZdA8PNgwMYXIsg8//8RBFNh7n5hI+205KS9gL/n3rZfq,iv:UoDvI0wu/gZQw8AFjpcK6qTGOLrz6fthNNBgwqqNl4Y=,tag:RXGFs38dcgqlHXYsIJ4Azw==,type:str]
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:8WehbewQSAAxvqnFGQ==,iv:NNcL8ADUC7duIFIQYOfn3xoTzkvKebvN5ipIao+v4oA=,tag:2sAqVISPPU4RbVTBllHltg==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:tHNNY9bIYBvyea4FoiAiTPrNCvA=,iv:IVHNn9htgHK2WrcYg3PvQW+O+e7yxQniQoMO+vJl18s=,tag:kwojsVQrfzzKokwUHZOxiQ==,type:str]
    LASTFM_APIKEY: ENC[AES256_GCM,data:bud4wleirvqnmv5AJBk7QgD28PYXX5rrOiBJDRbQMjs=,iv:QwMf7Ms7rvNIGmF55arXDj5+CvFdb0+xx/4afXOlWOI=,tag:SbbbIuL2za37LKscI2NFBQ==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:FCQyVu7/Y121Gz3gGLzmqIuq+JfV5wzmlv2qEgUPL0Q=,iv:M3q94EOd0Lr89Q8MRyI/lTXsyCm+te9TJc7MKARDMCM=,tag:e92pKgIcwhkr0AWdHeYOEQ==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIR216OFpBYzJ0ZS9jVEVF
            Vzl4cEpTSS9uck96M0kwNTkyNVI5RXhzbEFrCmFhREU1cGdMQ291Mkt6bTNnSlBk
            d3NtOUJGQi94cnhWUHpGeVlESzVZeWMKLS0tIG9nbGNkSXRNQm84dE9iQVZJTFJ3
            eXNlU2NPdFVja2lsakhvQmtPOGZkeEkK1DDB4AC/dS6zSHb3vMqR3HQ7zUc9RHIe
            byBD/Mj08sIg2feI6fbd89QdCZSQNizgr7sCMZvXlEpI9JRCk08nUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:06:15Z"
    mac: ENC[AES256_GCM,data:C9gcI14rrWwIgq2jfNiGRPwcaxR5nKA4ZeSBWLPmX5CpGjvSAx2Ckt/1jX2pmTBuPfd4OVj+7eQlrAY1CVQwXrTQlKamYyd2QTc1+ngtIYAX80+W8Ze0yAvmwS/fZUtE0SCPLFqGB6FYmDCb6UUZKtIU5Z1gyiz1mM4XyHTtCz8=,iv:JUbOf0fV01LdjLgZuIwgouyvYjfeMNhlEkkbJOzwYTk=,tag:9cCyMk8oEFgOvhsvBBmiXQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
