apiVersion: v1
kind: Secret
metadata:
    name: booklore-secrets
    namespace: books
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:QE/sq03jZdvYp+P1FyUklsC29pw=,iv:9u9dS8kYG1jiIH3ZVjwUpx3mUeB5DHMdPjCVrnM+qxo=,tag:REHIOZpMR1jpwYii53IG3g==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:pY1ZYEdySqTimTpSeFXucm8vhQQ=,iv:K56IJTmCED7sA5Tro/+hLCtzgaD01JEaJQ/Cd3LA10c=,tag:qgHfVLpHbu5+YhSSp3fqSw==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:yUPclPKv1urIJycvYfBIIV/dyWQ=,iv:EvFVuqMQfllkLyXti7iSYIpj0sXUcqRfDVc79rkKdto=,tag:SSIJ5WwkLHLgsFpUpn3XaQ==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWkJjZGxHN2RJb3BGczZp
            WjBEN1F4enlSMW84bnBKNXJUNnV4U1hQSTJVCmtZb3FUZ1MvamJ1NDJPa3luZG43
            cHJHcEIzOTBCQzBlalNjcEltdUxhZ2MKLS0tIEV3T3RPOXM3dkRlRmh2QjB2ZlU1
            djlMMk5idDc2d1lWQ1ZVR3Zqb2JJTGMKbxIk1gfRvWfFDLRkOz3ojNvGAMNf/gJ/
            3h+DQQ32UA7zHGZypxY9fDm4WTb4ASsogadWzoVeW24iHolxez2wvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T23:34:20Z"
    mac: ENC[AES256_GCM,data:0Jq8d9WtxSY5txJZ9R5FfmfSZnjO+pSBcbgYTowoSk4AXRPLVOmY0CdVKC4ylsmKQ+SDvoXZsGxouc3lGncnCW0ovLnpuLXedRl6Q1fR8pCg+tWpmuDADMeLDa4nNVcJ7fiQgcsuFMAo4DFekwJePTIYejLeco9Eby6NgBYDVeI=,iv:Un3bbBOYy8IZnSg9L7aqMmqs6y/uhlKgmz25HuYw/uM=,tag:auWHjl2f2miDUEDsC8SOHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
