apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  concurrency: 2
  cron: "0 4 * * *"
  groups:
  - critical
  labels:
    job: backup
  name: backup-daily
  retain: 90
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  concurrency: 3
  cron: "0 */6 * * *"
  groups:
  - default
  labels:
    job: snapshot
  name: snapshot-hourly
  retain: 14
  task: snapshot