---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nextcloud
  interval: 30m
  path: ./kubernetes/apps/selfhosted/nextcloud/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  targetNamespace: nextcloud
  wait: true
  dependsOn:
    - name: storage
  postBuild:
    substitute:
      APP: nextcloud
      HOSTNAME: nextcloud.${DOMAIN}
      LONGHORN_DUAL: ${LONGHORN_DUAL}
