apiVersion: v1
kind: Secret
metadata:
    name: freshrss
    namespace: freshrss
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IqKDFfA=,iv:z3TXXfmUgPinnWa7Iy8sOrMe0MwSRP+vT4jIHri0OjY=,tag:d0EJrbGT9Y7ga8zsweYEFg==,type:str]
    password: ENC[AES256_GCM,data:nDFWeH3Mtu0oKheOgOu5N/9yRZk=,iv:sg1ZNhePWyhQ+P9nEx8xBY0q4P5Eciplb4L4hQ1mgiI=,tag:gJTErfVT8llIrMlEPCBi2Q==,type:str]
sops:
    age:
        - recipient: age15khvgk6ygxragul9arzcvaznljxyvzfk3efcmn47tkr0chdlupxqq2eccv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajY2cDd5WEVrRDErV1Fn
            bk11VW5oQjI3MHhwTitScERiYUM4aXFrTXhZCk5vbGRCUnVSdmt1VGQ5M3QzS0cy
            eXd6a2ZQZlZ5cEJXOHFUd1R6TDZFRU0KLS0tIEdhTFcvcDFPUFU0aGI5ZEFMb1Rs
            NjB3WmRTSmpJNUI5bXNCNGh0cDVyWGsKbz2iJ1jP99vnD732ko9JkCx8adMmnQx7
            mk55VosQhET6V/M09aR1oVcRAegrIhWz0qvnP9qh88vi4tzJa5QYUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T15:59:09Z"
    mac: ENC[AES256_GCM,data:dp+cIpgjQByfaGP+vygNdEYlIBqZbO1gA6yWos7fvW8B9+T2IPVqEMZ2bmMFS5JerginCo380vLBUemnPnuhcPyOS7DOqBsqsTP2YSWsQf7SYgszDRcc2N5N//lcx0wtKdwsh3t7ElawgWNLVgBd9aY09vsk3pHKbUsht329g5c=,iv:Gmpp+ZcfNw1ZqFFjkTeVTMWnDBkVjRs7Im7pwTxKrn4=,tag:BheSQjeu/Wa1iVl97Zr5vQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
