apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps-network
resources:
  - metallb/ks.yaml
  - metallb-config/ks.yaml
  - traefik/ks.yaml
  - cert-manager/ks.yaml
  - tailscale/ks.yaml
  - pihole/ks.yaml
